import { supabase } from '@/lib/supabaseClient';
import type { Order, Recommendation } from '@/types';
import { generateRecommendations, detectOperationalSignals } from '@/logic/analysis';
import {
  calculateKpis,
  analyzeZones,
  calculatePeakMetrics,
  analyzeCancellationReasons,
} from '@/logic/calculations';

export interface AiAdvisorResult {
  recommendations: Recommendation[];
  aiPowered: boolean;
  message: string;
}

function buildContext(orders: Order[]) {
  const kpis = calculateKpis(orders);
  const zones = analyzeZones(orders);
  const peak = calculatePeakMetrics(orders);
  const reasons = analyzeCancellationReasons(orders);

  const zoneSummary = zones
    .map(
      (z) =>
        `${z.zone}: ${z.orders} orders, ${z.averageDeliveryTime.toFixed(1)} min avg delivery, ${z.cancellationRate.toFixed(1)}% cancel, ${z.riderUtilization.toFixed(1)}% rider util, ${z.inventoryAvailability.toFixed(1)}% inv avail`
    )
    .join('; ');

  const peakSummary = `Peak: ${peak.peak.avgDeliveryTime.toFixed(1)} min avg delivery, ${peak.peak.cancellationRate.toFixed(1)}% cancel, ${peak.peak.riderAvailability.toFixed(1)}% rider avail. Non-Peak: ${peak.nonPeak.avgDeliveryTime.toFixed(1)} min, ${peak.nonPeak.cancellationRate.toFixed(1)}% cancel, ${peak.nonPeak.riderAvailability.toFixed(1)}% rider avail.`;

  const cancellationReasons = reasons
    .slice(0, 5)
    .map((r) => `${r.reason}: ${r.count} (${r.percentage.toFixed(1)}%)`)
    .join('; ');

  return { kpis, zoneSummary, peakSummary, cancellationReasons };
}

export async function fetchAiRecommendations(
  orders: Order[]
): Promise<AiAdvisorResult> {
  const signals = detectOperationalSignals(orders);
  const { kpis, zoneSummary, peakSummary, cancellationReasons } = buildContext(orders);

  const functionUrl = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/ai-advisor`;

  try {
    const { data: sessionData } = await supabase.auth.getSession();
    const accessToken = sessionData.session?.access_token;

    const response = await fetch(functionUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${accessToken ?? import.meta.env.VITE_SUPABASE_ANON_KEY}`,
        apikey: import.meta.env.VITE_SUPABASE_ANON_KEY,
      },
      body: JSON.stringify({
        kpis,
        signals,
        zoneSummary,
        peakSummary,
        cancellationReasons,
      }),
    });

    if (!response.ok) {
      throw new Error(`Request failed (${response.status})`);
    }

    const data = await response.json();

    if (data.aiPowered && Array.isArray(data.recommendations)) {
      const recs: Recommendation[] = data.recommendations.map(
        (r: Record<string, string>, i: number) => ({
          id: `ai-rec-${i}`,
          problem: r.problem ?? '',
          evidence: r.evidence ?? '',
          recommendedAction: r.recommendedAction ?? '',
          expectedDirection: r.expectedDirection ?? '',
          riskOrLimitation: r.riskOrLimitation ?? '',
          validationStep: r.validationStep ?? '',
        })
      );
      return {
        recommendations: recs,
        aiPowered: true,
        message: 'Recommendations generated by Google Gemini AI.',
      };
    }

    // Fall back to rule-based
    const ruleRecs = generateRecommendations(orders).map((r) => ({
      ...r,
      validationStep: 'Validate this recommendation against operational data before implementation.',
    }));
    return {
      recommendations: ruleRecs,
      aiPowered: false,
      message: data.message ?? 'Using rule-based recommendations (AI not configured).',
    };
  } catch {
    // Fall back to rule-based on any error
    const ruleRecs = generateRecommendations(orders).map((r) => ({
      ...r,
      validationStep: 'Validate this recommendation against operational data before implementation.',
    }));
    return {
      recommendations: ruleRecs,
      aiPowered: false,
      message: 'AI service unavailable. Using rule-based recommendations.',
    };
  }
}
